# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        compiler: [clang, clang++, gcc, g++]
        include:
          - compiler: clang
            file-ext: c
          - compiler: gcc
            file-ext: c
          - compiler: clang++
            file-ext: cpp
          - compiler: g++
            file-ext: cpp

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "10.0"
          directory: ${{ runner.temp }}/llvm

      - name: Build
        env:
          EXT: ${{ matrix.file-ext }}
        run: .\scripts\build_clang_gcc.bat --output scale_test_c.exe --compiler ${{ matrix.compiler }} --config debug --source demos\scale_test_c\scale_test_c.%EXT%

      - name: Run
        run: .\bin\win64\${{ matrix.compiler }}\debug\demos\scale_test_c.exe

  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [clang, clang++, gcc, g++]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install LLVM and Clang
        run: sudo apt install clang gcc

      - name: Build
        env:
          EXT: ${{ matrix.file-ext }}
        run: ./scripts/build_clang_gcc.sh --output scale_test_c.exe --compiler ${{ matrix.compiler }} --config debug --source demos/scale_test_c/scale_test_c.$EXT

      - name: Run
        run: ./bin/linux/${{ matrix.compiler }}/debug/demos/scale_test_c.exe