# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Steps represent a sequence of tasks that will be executed as part of the job
  steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install LLVM and Clang
      runs-on: self-hosted
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "10.0"
        directory: ${{ runner.temp }}/llvm

    - name: Build
      runs-on: self-hosted
      strategy:
        matrix:
        compiler: [clang, gcc]
      run: .\scripts\build_clang_gcc.bat --output filtering.exe --compiler ${{ matrix.compiler }} --config debug --source demos\filtering\filtering.c

    - name: Run
      runs-on: self-hosted
      strategy:
        matrix:
        compiler: [clang, gcc]
      run: .\bin\win64\${{ matrix.compiler }}\debug\demos\filtering.exe
